### ISSUE TITLE
Feat: 라운지 페이지 구현

### ISSUE THREAD

**Issue by wuchangb** [FINALALT1/BACKEND#19]
## Description

> 라운지 페이지 구현

## Tasks

- [x] 컨텐츠 검색 API
- [x] 라운지 메인페이지 조회 API
- [x] 전체 컨텐츠 가져오기 API
- [x] 핫한 컨텐츠 가져오기 API
- [x] 통합테스트
