### ISSUE TITLE
Feat: 회원가입 기능 구현

### ISSUE THREAD

**Issue by CHITSOO** [FINALALT1/BACKEND#20]
## Description

> 투자자 회원가입 API
> PB 회원 가입 API

## Tasks
- [x] 투자자 회원가입 API
- [x] PB 회원 가입 API (명함 이미지 파일 저장하는 부분 제외)
- [x] S3 연동 후 압축해서 이미지 파일 올리기
- [x] swagger로 API 문서
- [ ] PB 회원가입 관련 단위 테스트 코드
