### ISSUE TITLE
백로그

### ISSUE THREAD

**Issue by CHITSOO** [FINALALT1/BACKEND#213]
## Description

> 추가적으로 할 것들

## Tasks

- [x] count 쿼리 반환 타입 Long으로 바꾸기
- [x] 백오피스 게시물 삭제 API 추가 + Test + Swagger
- [x] 더미데이터 중 디폴트 데이터(증권사, 지점, 자주 묻는 질문) 추가
- [x] Jacoco로 테스트 커버리지 측정
