### ISSUE TITLE
Feat: 컨텐츠 상세 페이지 보기 기능 구현 

### ISSUE THREAD

**Issue by wuchangb** [FINALALT1/BACKEND#31]
## Description

> 컨텐츠 상세보기 및 북마크하기, 북마크 취소하기API 구현

## Tasks

- [x] 컨텐츠 상세 페이지 가져오기 API
- [x] 컨텐츠 북마크하기 API
- [x] 컨텐츠 북마크 취소하기 API
- [x] 통합 테스트
- [x] SWAGGER
